# -*- coding: utf-8 -*-
"""GPTAPI_test.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1M7SMyrDnhauWcmnD6wmz9sZbGXS0UeLs
"""

!pip install -U python-dotenv

import openai
import os

# 서드 파티 라이브러리를 가져옵니다
from dotenv import load_dotenv, find_dotenv

# 시스템의 환경 변수를 읽어옵니다
_ = load_dotenv(find_dotenv())

# API_KEY를 설정합니다
openai.api_key  = os.getenv('OPENAI_API_KEY')

# OpenAI 인터페이스를 감싸는 함수, 매개변수는 프롬프트, 반환 값은 해당 결과
def get_completion(prompt, model="gpt-3.5-turbo"):
    '''
    prompt: 해당 프롬프트
    model: 사용되는 모델, 기본 값은 gpt-3.5-turbo(ChatGPT), 베타 테스트에 참여한 사용자는 gpt-4를 선택할 수 있습니다.
    '''
    messages = [{"role": "user", "content": prompt}]
    response = openai.ChatCompletion.create(
        model=model,
        messages=messages,
        temperature=0, # 모델 출력의 온도 계수, 출력의 랜덤성을 제어합니다
    )
    # OpenAI의 ChatCompletion 인터페이스를 호출합니다
    return response.choices[0].message["content"]

from openai import OpenAI
import os


from google.colab import userdata
userdata.get('OPENAI_API_KEY')


# Google Colab의 '보안 비밀' 기능을 사용 중이라면 아래와 같이 클라이언트를 설정하세요
# 직접 환경 변수를 설정했다면 os.environ.get('OPENAI_API_KEY')를 사용하세요
client = OpenAI(api_key=userdata.get('OPENAI_API_KEY'))

def get_completion(prompt, model="gpt-3.5-turbo"):
    messages = [{"role": "user", "content": prompt}]

    # 최신 1.0.0+ 문법: client.chat.completions.create
    response = client.chat.completions.create(
        model=model,
        messages=messages,
        temperature=0
    )

    return response.choices[0].message.content

# 실행 테스트
text = get_completion("자바언어의 5가지 특징을 알려줘")
print(text)