# -*- coding: utf-8 -*-
"""qween-tts-WebUI-Character.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WUZgSPIat4RqY2E9XXDHqGxnEa43tS1s
"""

# 필수 패키지 설치
!pip install -U qwen-tts

# (선택 사항) GPU 메모리 절약 및 속도 향상을 위한 FlashAttention 2 설치
# !pip install -U flash-attn --no-build-isolation

import torch
import gradio as gr
import numpy as np
from PIL import Image, ImageDraw

from qwen_tts import Qwen3TTSModel

# =========================
# 1. 모델 로드
# =========================
model_id = "Qwen/Qwen3-TTS-12Hz-0.6B-CustomVoice"

print("모델을 불러오는 중입니다...")

model = Qwen3TTSModel.from_pretrained(
    model_id,
    device_map="cuda:0",
    dtype=torch.bfloat16
)

supported_speakers = model.get_supported_speakers()

# =========================
# 2. 화자 정보
# =========================
speaker_info = {
    "aiden": "Aiden",
    "dylan": "Dylan",
    "eric": "Eric",
    "ono_anna": "Ono Anna",
    "ryan": "Ryan",
    "serena": "Serena",
    "sohee": "Sohee",
    "uncle_fu": "Uncle Fu",
    "vivian": "Vivian"
}

# =========================
# 3. 가상 프로필 이미지 생성
# =========================
def create_dummy_avatar(name):
    """
    실제 이미지 대신 가상 프로필 이미지를 생성
    """

    img = Image.new("RGB", (220, 220), color=(40, 40, 60))
    draw = ImageDraw.Draw(img)

    # 원형 얼굴
    draw.ellipse((40, 30, 180, 170), fill=(120, 170, 255))

    # 눈
    draw.ellipse((80, 80, 95, 95), fill="black")
    draw.ellipse((125, 80, 140, 95), fill="black")

    # 입
    draw.arc((80, 100, 140, 140), start=0, end=180, fill="black", width=3)

    # 이름
    draw.text((60, 185), name, fill="white")

    return np.array(img)

speaker_images = []

for speaker in supported_speakers:
    speaker_images.append((
        create_dummy_avatar(speaker_info.get(speaker, speaker)),
        speaker
    ))

# =========================
# 4. 음성 생성 함수
# =========================
def generate_audio(text, speaker):

    if not text.strip():
        return None

    print(f"{speaker} 목소리 생성 중...")

    wavs, sr = model.generate_custom_voice(
        text,
        language="Korean",
        speaker=speaker
    )

    return (sr, wavs[0])

# =========================
# 5. 이미지 클릭 처리
# =========================
def select_speaker(evt: gr.SelectData):

    selected_index = evt.index
    selected_speaker = supported_speakers[selected_index]

    return selected_speaker, f"선택된 화자: {selected_speaker}"

# =========================
# 6. Gradio UI
# =========================
with gr.Blocks(title="Qwen3-TTS Image UI") as demo:

    gr.Markdown("# 🎙️ Qwen3-TTS 이미지 기반 화자 선택")
    gr.Markdown("이미지를 클릭하여 화자를 선택하세요.")

    selected_speaker = gr.State(
        value=supported_speakers[0]
    )

    with gr.Row():

        with gr.Column(scale=1):

            text_input = gr.Textbox(
                label="입력 텍스트",
                lines=7,
                placeholder="텍스트를 입력하세요..."
            )

            speaker_gallery = gr.Gallery(
                value=speaker_images,
                label="화자 선택",
                columns=3,
                height=500,
                object_fit="contain",
                allow_preview=False
            )

            selected_text = gr.Markdown(
                f"선택된 화자: {supported_speakers[0]}"
            )

            generate_btn = gr.Button(
                "음성 생성하기",
                variant="primary"
            )

        with gr.Column(scale=1):

            audio_output = gr.Audio(
                label="생성 결과",
                type="numpy"
            )

    # 이미지 클릭 이벤트
    speaker_gallery.select(
        fn=select_speaker,
        outputs=[selected_speaker, selected_text]
    )

    # 음성 생성 버튼
    generate_btn.click(
        fn=generate_audio,
        inputs=[text_input, selected_speaker],
        outputs=audio_output
    )

# =========================
# 7. 실행
# =========================
demo.launch(
    share=True,
    debug=True
)