# -*- coding: utf-8 -*-
"""qwen-tts 화자 클론_UI개선.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1RHvmgU3oAyQcSNKM3US-JBLKEQ3Bfg84
"""

# 필수 패키지 설치
!pip install -U qwen-tts

# (선택 사항) GPU 메모리 절약 및 속도 향상을 위한 FlashAttention 2 설치
# !pip install -U flash-attn --no-build-isolation

import nest_asyncio
nest_asyncio.apply()

import torch
import gradio as gr
from qwen_tts import Qwen3TTSModel

# 이전 실행 캐시 초기화 (필요시 추가)
gr.close_all()

# ==========================================
# 1. 모델 로드 (목소리 복제를 위해 Base 모델 사용)
# ==========================================
model_id = "Qwen/Qwen3-TTS-12Hz-0.6B-Base"
model = Qwen3TTSModel.from_pretrained(
    model_id,
    device_map="cuda:0",
    dtype=torch.bfloat16
)

# ==========================================
# 2. 음성 복제 추론 함수
# ==========================================
def clone_voice_tts(text, reference_audio, reference_text):
    """
    text: 생성하고 싶은 문장
    reference_audio: 목소리 샘플 파일 경로
    reference_text: 목소리 샘플이 실제로 말하고 있는 내용 (대본)
    """
    if text.strip() == "":
        return None
    if reference_audio is None:
        return None

    # 참조 텍스트가 비어있을 경우에 대한 처리
    ref_txt = reference_text.strip() if reference_text else ""

    print(f"사용자 목소리 분석 및 생성 시작... (참조 대본 유무: {bool(ref_txt)})")

    # Qwen3-TTS 공식 API:
    # ref_text를 제공하면 x_vector_only_mode를 False로 하여 더 정밀한 학습(In-Context Learning)을 수행합니다.
    wavs, sr = model.generate_voice_clone(
        text=text,
        ref_audio=reference_audio,
        ref_text=ref_txt,
        x_vector_only_mode=False if ref_txt else True, # 대본이 있으면 정밀 모드, 없으면 특징점 추출 모드
        language="Korean"
    )

    return (sr, wavs[0])

# ==========================================
# 3. Gradio 인터페이스 구성
# ==========================================
with gr.Blocks(title="Advanced Qwen3-TTS Voice Cloner") as demo:
    gr.Markdown("# 🎤 Qwen3-TTS 정밀 목소리 복제")
    gr.Markdown("참조 음성과 그 음성의 **대본(Transcript)**을 함께 입력하면 훨씬 더 정확한 목소리 복제가 가능합니다.")

    with gr.Row():
        # 왼쪽 컬럼: 입력 설정
        with gr.Column():
            with gr.Group():
                gr.Markdown("### 1. 내 목소리 샘플 등록")
                reference_audio = gr.Audio(
                    label="참조 음성 업로드 (10~30초 권장)",
                    type="filepath")
                reference_text = gr.Textbox(
                    label="참조 음성 대본 (Transcription)",
                    placeholder="위 업로드한 음성 파일에서 말하고 있는 내용을 그대로 적어주세요.",
                    lines=3
                )

            with gr.Group():
                gr.Markdown("### 2. 변환할 텍스트 입력")
                text_input = gr.Textbox(
                    label="새로 읽을 문장",
                    lines=5,
                    placeholder="내 목소리로 읽게 하고 싶은 내용을 입력하세요..."
                )

            generate_btn = gr.Button(
                "내 목소리로 AI 음성 생성",
                variant="primary"
            )

        # 오른쪽 컬럼: 결과 출력
        with gr.Column():
            gr.Markdown("### 3. 생성 결과")
            audio_output = gr.Audio(
                label="복제된 AI 목소리",
                type="numpy"
            )

    # 버튼 클릭 이벤트 연결
    generate_btn.click(
        fn=clone_voice_tts,
        inputs=[text_input, reference_audio, reference_text],
        outputs=audio_output
    )

# 실행
demo.launch(
    share=True,
    debug=True
)

""" 🛠 수정 사항 요약
1.  **UI 추가**: `reference_text`라는 `gr.Textbox`를 추가하여 참조 음성의 내용을 입력할 수 있도록 했습니다.
2.  **함수 인자 확장**: `clone_voice_tts` 함수가 `reference_text`를 인자로 받도록 수정했습니다.
3.  **모델 파라미터 최적화**:
    *   `ref_text=ref_txt`: 입력한 대본 정보를 모델에 전달합니다.
    *   `x_vector_only_mode`: 대본이 입력된 경우 `False`로 설정되어, 모델이 단순한 목소리 특징 추출을 넘어 오디오와 텍스트의 상관관계를 학습하는 **In-Context Learning** 모드로 동작하게 했습니다. 이는 복제된 음성의 안정성과 유사도를 크게 높여줍니다.

Qwen3-TTS 기술에 대한 상세한 프레젠테이션과 수정된 코드가 준비되었습니다. 확인해 보시고 추가로 필요하신 부분이 있다면 말씀해 주세요!
"""